#!/usr/bin/env bash
# print domains and subdomains to make our life easier


print_subdomain_info() {
    local domain=$1
    local subdomain=$2
    local result=$(dig "$subdomain.$domain" +short)
    if [ -n "$result" ]; then
        echo "The subdomain $subdomain is a $(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/ {getline; print $4}') record and points to $result"
    else
        echo "The subdomain $subdomain does not exist for domain $domain"
    fi
}

if [ "$#" -eq 2 ]; then
    print_subdomain_info "$1" "$2"
else
    print_subdomain_info "$1" "www"
    print_subdomain_info "$1" "lb-01"
    print_subdomain_info "$1" "web-01"
    print_subdomain_info "$1" "web-02"
fi

