#!/usr/bin/env bash
# print domains and subdomains

print_subdomain_info() {
    local domain=$1
    local subdomain=$2
    dig "$subdomain.$domain" | awk '/ANSWER SECTION:/ {getline; print "The subdomain " $1 " is a " $4 " record and points to " $5}'
}

if [ "$#" -eq 2 ]; then
    print_subdomain_info "$1" "$2"
else
    print_subdomain_info "$1" "www"
    print_subdomain_info "$1" "lb-01"
    print_subdomain_info "$1" "web-01"
    print_subdomain_info "$1" "web-02"
fi

