#!/usr/bin/env bash
#Install nginx web server
apt-get update
apt-get install -y nginx
echo "server { listen 80; server_name _;
root /var/www/html;
index index.html;
location / { echo 'Hello World!';
}
}" > /etc/nginx/sites-available/default

service nginx restart
