#!/usr/bin/env bash
#Install nginx
# Update the package lists
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Configure nginx
sudo sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default
sudo sed -i '/listen \[::\]:80 default_server/ a \\treturn 200 "Hello World!";' /etc/nginx/sites-available/default

service nginx start
