#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page
apt-get update
apt-get install -y nginx
echo "server {
    listen 80;
    listen [::]:80;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/redirect_me
ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/
service nginx restart
