#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page
apt-get update
apt-get install -y nginx
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
echo "server {
    listen 80;
    listen [::]:80;
    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-available/custom_404
ln -sf /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default
service nginx restart
