#!/usr/bin/env bash
#configure nginx to port 80
#sed -i 's/#listen 80;/listen 80 default_server;/g' /etc/nginx/nginx.conf
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
