#!/usr/bin/env bash
#Bash script that Process and PID file
terminating() {
	echo "I hate the kill command"
	cleanup
}
interrupting() {
	echo "Y U no love me?!"
}
quitting() {
	cleanup
}
cleanup() {
	rm -f /var/run/myscript.pid
	exit 0
}
trap 'terminating' SIGTERM
trap 'interrupting' SIGINT
trap 'quitting' SIGQUIT

echo $$ > /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
	sleep 2
done
