#!/usr/bin/env bash
#Bash script that stops 4-to_infinity_and_beyond process without kill or killall
pkill -f "bash ./4-to_infinity_and_beyond"
if pgrep -f "bash ./4-to_infinity_and_beyond" >/dev/null; then
	echo "Process not stopped."
fi
