#!/usr/bin/env bash
# Bash script that configures an Ubuntu server
cp /etc/hosts ~/hosts.backup

sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.backup
#sed -i '2i8.8.8.8 facebook.com' ~/etc/hosts
echo '8.8.8.8 facebook.com' >> ~/hosts.backup
cp -f ~/hosts.backup /etc/hosts
