#!/usr/bin/env bash
#Run Nginx as Nginx
sed -i 's/user\s*\(.*\);/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*\(.*\);/listen 8080 default_server;/g' /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
