#!/usr/bin/env bash
#7 lines or less
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
